---

- name: "Install apt package"
  apt: name=hostapd

- name: "Create configuration file"
  template: src=hostapd.conf.j2 dest=/etc/hostapd/hostapd.conf
  notify: ["Restart hostapd"]

- name: "Set configuration file path for deamon"
  lineinfile:
    dest: /etc/default/hostapd
    regexp: '^#?DAEMON_CONF=".*"'
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: ["Restart hostapd"]
